name=Integrall
version=1.0.0
author=Emmanuel TIGO
maintainer=Emmanuel TIGO <emmanuel@example.com>
sentence=Unified IoT firmware framework for ESP32/ESP8266.
paragraph=Simplifies hardware integration (Relays, OLEDs, LCDs, BME280, DHT, Keypads) and handles backend communication automatically.
category=Communication
url=https://integrall.io
architectures=esp32,esp8266,avr
depends=ArduinoJson, LiquidCrystal_I2C, Keypad, ESP32Servo, Adafruit SSD1306, Adafruit GFX Library, Adafruit Unified Sensor, DHT sensor library, Adafruit BME280, OneWire, DallasTemperature
includes=Integrall.h
