name=Integrall
version=0.1.0
author=Emmanuel TIGO
maintainer=Emmanuel TIGO <emmanuel@example.com>
sentence=Unified IoT firmware framework for ESP32.
paragraph=Simplifies hardware integration (Relays, LCDs, Keypads) and handles backend communication automatically.
category=Communication
url=https://integrall.io
architectures=esp32,esp8266,avr
depends=ArduinoJson, LiquidCrystal_I2C, Keypad, ESP32Servo, Adafruit SSD1306, DHT sensor library
includes=Integrall.h
